services:
  db:
    image: postgis/postgis:16-3.4
    container_name: coordinate_db
    restart: always
    environment:
      POSTGRES_DB: tabaco_retail
      POSTGRES_USER: Team_ten
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./db/init_db.sql:/docker-entrypoint-initdb.d/1_init_db.sql
      - ./db/import_data.sql:/docker-entrypoint-initdb.d/2_import_data.sql
      - ./db/data/:/docker-entrypoint-initdb.d/data/
    networks:
      